#!/bin/sh

random_number=$(lib-random-number)
random_index=$(($random_number % $# + 1))
# this eval is okay because there is no scope for code injection
# and the function is unset at the end
eval "printf %s \${$random_index}"
