#!/bin/sh


# Variables
# ------------------------------------------------------------------------------
version='0.0.1'
scratch_dir=${SCRATCH_DIR:-"$HOME/scratches"}
dot_scratch_dir="$HOME/.scratch/repos"




# Scratch command
# ------------------------------------------------------------------------------
scratch() {
  local name
  name="scratch-$(rand_word)"
  cd $scratch_dir &&
  mkdir -p $name &&
  cd $name
  return 0
}


# Pass argv
# ------------------------------------------------------------------------------
[ "$#" -eq 0 ] && scratch && exit
case "$1" in
  -h|--help)    help;                 exit;;
  -v|--version) version;              exit;;
  list)         list;                 exit;;
  install)      install $@;           exit;;
  # *)            scratch_installed $@; exit;;
esac

