#!/bin/sh

dir=$1

# if its a dir
if [ -d "$dir" ]; then

  # but not writable by this process
  if [ ! -w "$dir" ]; then
    printf "\nYour scratch directory %s is not writable. Try:" "$dir"
    printf "  chmod +x %s\n" "$dir"
    exit 1
  fi

# or it is not a directory
else

  # but is instead a file
  if [ -f "$dir" ]; then
    printf "\nYour scratch directory %s is not a directory\n" "$dir"
    exit 1

  # or just doesn't exist
  else
    mkdir -p "$dir"
    if [ $? -eq 1 ]; then
      printf "\nFailed to create %s\n" "$dir"
      exit 1
    fi
    # success! directory now exists
  fi
fi
